### ISSUE TITLE
signTransaction queue

### ISSUE THREAD

**Issue by jarradh** [status-im/go-ethereum#15]
when transaction is signed the account needs to be unlocked first, so we need to prompt the user with the details of the transaction and ask for password in the gui of the application

This would mean informing react-native of the transactions require to be signed.

Later we will also want to do more sophisticated management, ie allowing the user to "remember password for similar transactions"

**Comment by farazdagi** [comment]
**Jarrad:**

- You can think of the ethereum protocols as being an extension to html/js development. That is in javascript there is a new object called `web3`, in reality this web3 object is a SHIM to a JSON-RPC server running locally, which exposes a bunch of methods to interacting with Ethereum
-  one of these is sendTransaction(), this lets you change the state of the blockchain (if you have money to pay for it) https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction
- this is a dangerous command because it actually spends or sends a users money
- now in normal operation, the account is usually locked, if the account is locked, sendTransaction method fails, we want to keep the account locked at all times, and we want to require the user to enter their password when a sendTransaction is requested
- in order to do so, we need to intercept when this sendTransaction is called, then we need to notify React Native (via Java/Objective-C there should be code for doing this already), and it will validate the transaction (user views and enters password) and returns to complete the transaction on Go side

- **IMPORTANT:** however we want this to be async/non-blocking and we need to account for multiple transactions accumulating

**Corresponding code in status-go bindings:**
-  https://github.com/status-im/status-go/blob/node-object-jni/src/library.c#L132
- https://github.com/status-im/status-go/blob/node-object-jni/src/library.c#L205
- https://github.com/status-im/status-go/commit/96c1b5ec40153fa31fc891d5313b45b271e380b6 (whisper message notification example)

**Extra:**
- works started (by Daniel): https://github.com/status-im/go-ethereum/commit/b31b711ddfbe2467872ca8b87b6486eddb306f2c (basically, send transaction now only adds to the channel.  We then need to "complete transaction" as you process from the channel, where "complete transaction" is the functionality that was previously in send transaction)
- related to https://github.com/status-im/status-go/issues/18
